/* ***************************************************************
* Autor............: Guilherme Oliveira
* Inicio...........: 18/06/2024 - 15:57
* Ultima alteracao.: 01/07/2024 - 14:33
* Nome.............: Transito Automato
* Funcao...........: Classe que armazena e retorna o roteiro que cada carro ira seguir para realizar seu percuso sem colisao, a posicao
  inicial de cada carro e o sentido
*************************************************************** */
package util;

public enum Percursos
{
  INFORMACAO_DE_PERCURSO;
  
  private final int VIRAR_DIREITA = 0; //Indica que o carro deve se mover para direita
  private final int VIRAR_ESQUERDA = 1; //Indica que o carro deve se mover para esquerda
  private final int SEGUIR_RETO = 2; //Indica que o carro deve se manter em linha reta
  private final int ADQUIRIR_SEMAFORO = 3;//Indica que o carro deve tentar possuir o proximo semaforo do seu percurso
  
  private final int LIBERAR_SEMAFORO_DE_INICIO = 4;//Libera o semaforo que o carro ja comeca possuindo
  private final int LIBERAR_SEMAFORO_DE_INICIO_DUPLO = 5;
  private final int LIBERAR_SEMAFORO_DE_INICIO_QUADRUPLO = 7;
  
  private final int LIBERAR_ULTIMO_SEMAFORO = 8;//Libera o ultimo semaforo que o carro adquiriu,
  private final int LIBERAR_PENULTIMO_SEMAFORO = 9;//Libera o penultimo e assim por diante
  private final int LIBERAR_ANTEPENULTIMO_SEMAFORO = 10;
  private final int LIBERAR_PRE_ANTEPENULTIMO_SEMAFORO = 11;
  private final int LIBERAR_PRE2X_ANTEPENULTIMO_SEMAFORO = 12;
  private final int LIBERAR_PRE3X_ANTEPENULTIMO_SEMAFORO = 13;
  private final int LIBERAR_PRE4X_ANTEPENULTIMO_SEMAFORO = 14;
  private final int LIBERAR_PRE5X_ANTEPENULTIMO_SEMAFORO = 15;
  private final int LIBERAR_PRE8X_ANTEPENULTIMO_SEMAFORO = 18;
  private final int LIBERAR_PRE9X_ANTEPENULTIMO_SEMAFORO = 19;
  private final int LIBERAR_PRE10X_ANTEPENULTIMO_SEMAFORO = 20;
  
  /* Essa matriz armazena os vetores percurso de cada carro, cada vetor da matriz descreve
     as acoes que cada carro ira realizar respectivamente */
  private final int[][] PERCURSOS  = 
  {
    {
      ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, VIRAR_DIREITA, LIBERAR_ULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO,
      LIBERAR_ULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, VIRAR_ESQUERDA,
      LIBERAR_ANTEPENULTIMO_SEMAFORO, SEGUIR_RETO, LIBERAR_ULTIMO_SEMAFORO, VIRAR_ESQUERDA, SEGUIR_RETO, ADQUIRIR_SEMAFORO,
      ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_PRE2X_ANTEPENULTIMO_SEMAFORO, LIBERAR_ULTIMO_SEMAFORO,
      SEGUIR_RETO, LIBERAR_PENULTIMO_SEMAFORO, SEGUIR_RETO, LIBERAR_ANTEPENULTIMO_SEMAFORO, VIRAR_ESQUERDA, ADQUIRIR_SEMAFORO,
      ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, SEGUIR_RETO, LIBERAR_ULTIMO_SEMAFORO,
      LIBERAR_PRE10X_ANTEPENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO,
      SEGUIR_RETO, LIBERAR_PRE4X_ANTEPENULTIMO_SEMAFORO, LIBERAR_ULTIMO_SEMAFORO, LIBERAR_PRE2X_ANTEPENULTIMO_SEMAFORO, SEGUIR_RETO,
      LIBERAR_PRE3X_ANTEPENULTIMO_SEMAFORO, VIRAR_ESQUERDA, ADQUIRIR_SEMAFORO, SEGUIR_RETO, ADQUIRIR_SEMAFORO,
      ADQUIRIR_SEMAFORO, SEGUIR_RETO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_ULTIMO_SEMAFORO,
      LIBERAR_ANTEPENULTIMO_SEMAFORO, LIBERAR_PRE2X_ANTEPENULTIMO_SEMAFORO, LIBERAR_PRE4X_ANTEPENULTIMO_SEMAFORO,
      LIBERAR_PRE_ANTEPENULTIMO_SEMAFORO, SEGUIR_RETO, VIRAR_ESQUERDA, ADQUIRIR_SEMAFORO, SEGUIR_RETO, ADQUIRIR_SEMAFORO,
      ADQUIRIR_SEMAFORO, VIRAR_ESQUERDA, LIBERAR_PRE2X_ANTEPENULTIMO_SEMAFORO, LIBERAR_ANTEPENULTIMO_SEMAFORO, LIBERAR_ULTIMO_SEMAFORO,
      LIBERAR_PRE8X_ANTEPENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, 
      LIBERAR_ANTEPENULTIMO_SEMAFORO, LIBERAR_ULTIMO_SEMAFORO, LIBERAR_PRE2X_ANTEPENULTIMO_SEMAFORO, VIRAR_DIREITA,
      LIBERAR_PENULTIMO_SEMAFORO
    },
    
    
    {
      ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO,
      LIBERAR_ULTIMO_SEMAFORO, LIBERAR_SEMAFORO_DE_INICIO, SEGUIR_RETO, LIBERAR_PENULTIMO_SEMAFORO, VIRAR_DIREITA, SEGUIR_RETO,
      ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_PRE3X_ANTEPENULTIMO_SEMAFORO,
      LIBERAR_PRE4X_ANTEPENULTIMO_SEMAFORO, LIBERAR_ULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_ANTEPENULTIMO_SEMAFORO,
      SEGUIR_RETO, LIBERAR_PRE_ANTEPENULTIMO_SEMAFORO, VIRAR_DIREITA, ADQUIRIR_SEMAFORO, SEGUIR_RETO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO,
      VIRAR_DIREITA, LIBERAR_ANTEPENULTIMO_SEMAFORO, LIBERAR_ULTIMO_SEMAFORO, LIBERAR_PRE9X_ANTEPENULTIMO_SEMAFORO,
      LIBERAR_PRE10X_ANTEPENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_ULTIMO_SEMAFORO, LIBERAR_PRE2X_ANTEPENULTIMO_SEMAFORO, 
      ADQUIRIR_SEMAFORO, SEGUIR_RETO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, VIRAR_ESQUERDA, LIBERAR_ANTEPENULTIMO_SEMAFORO,
      LIBERAR_ULTIMO_SEMAFORO, LIBERAR_PRE3X_ANTEPENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO,
      LIBERAR_PRE_ANTEPENULTIMO_SEMAFORO, LIBERAR_ULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO,
      ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_PRE3X_ANTEPENULTIMO_SEMAFORO, LIBERAR_ULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO,
      VIRAR_DIREITA,  LIBERAR_ULTIMO_SEMAFORO, LIBERAR_PRE_ANTEPENULTIMO_SEMAFORO, SEGUIR_RETO, VIRAR_DIREITA, ADQUIRIR_SEMAFORO,
      SEGUIR_RETO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_PRE_ANTEPENULTIMO_SEMAFORO, LIBERAR_PENULTIMO_SEMAFORO,
      LIBERAR_PRE5X_ANTEPENULTIMO_SEMAFORO, LIBERAR_PRE4X_ANTEPENULTIMO_SEMAFORO
    },
    
    
    {
      ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_SEMAFORO_DE_INICIO_DUPLO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO,
      LIBERAR_ANTEPENULTIMO_SEMAFORO, LIBERAR_ULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO,
      LIBERAR_PRE_ANTEPENULTIMO_SEMAFORO, LIBERAR_ULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO,
      ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_PRE3X_ANTEPENULTIMO_SEMAFORO, LIBERAR_ULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO,
      VIRAR_DIREITA, LIBERAR_PRE_ANTEPENULTIMO_SEMAFORO, LIBERAR_ULTIMO_SEMAFORO, SEGUIR_RETO, VIRAR_DIREITA, ADQUIRIR_SEMAFORO,
      SEGUIR_RETO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_PRE_ANTEPENULTIMO_SEMAFORO, LIBERAR_PENULTIMO_SEMAFORO,
      LIBERAR_PRE5X_ANTEPENULTIMO_SEMAFORO, LIBERAR_PRE4X_ANTEPENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO,
      ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_ULTIMO_SEMAFORO, LIBERAR_PRE2X_ANTEPENULTIMO_SEMAFORO, SEGUIR_RETO, 
      LIBERAR_PENULTIMO_SEMAFORO, VIRAR_DIREITA, SEGUIR_RETO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, VIRAR_DIREITA, 
      LIBERAR_ULTIMO_SEMAFORO, LIBERAR_PRE2X_ANTEPENULTIMO_SEMAFORO, LIBERAR_PRE3X_ANTEPENULTIMO_SEMAFORO
    },
    
    
    {
      ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_ULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_ULTIMO_SEMAFORO,
      LIBERAR_ANTEPENULTIMO_SEMAFORO, SEGUIR_RETO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, VIRAR_ESQUERDA,
      ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_ANTEPENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, VIRAR_ESQUERDA, 
      LIBERAR_ULTIMO_SEMAFORO, LIBERAR_PRE3X_ANTEPENULTIMO_SEMAFORO, LIBERAR_PRE_ANTEPENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO,
      LIBERAR_ANTEPENULTIMO_SEMAFORO, LIBERAR_PRE_ANTEPENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO,
      LIBERAR_ANTEPENULTIMO_SEMAFORO, LIBERAR_ULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO,
      LIBERAR_PRE_ANTEPENULTIMO_SEMAFORO, LIBERAR_ULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO,
      LIBERAR_PRE2X_ANTEPENULTIMO_SEMAFORO, LIBERAR_ULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO,
      VIRAR_ESQUERDA, LIBERAR_PRE3X_ANTEPENULTIMO_SEMAFORO, LIBERAR_PRE2X_ANTEPENULTIMO_SEMAFORO, LIBERAR_ULTIMO_SEMAFORO, SEGUIR_RETO,
      LIBERAR_PENULTIMO_SEMAFORO, VIRAR_ESQUERDA, LIBERAR_ANTEPENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_ULTIMO_SEMAFORO
    },
    
    
    {
      VIRAR_DIREITA, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, ADQUIRIR_SEMAFORO,
      ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_ULTIMO_SEMAFORO, LIBERAR_PRE3X_ANTEPENULTIMO_SEMAFORO,
      LIBERAR_PRE2X_ANTEPENULTIMO_SEMAFORO, LIBERAR_PRE_ANTEPENULTIMO_SEMAFORO, SEGUIR_RETO, VIRAR_DIREITA, ADQUIRIR_SEMAFORO, SEGUIR_RETO,
      VIRAR_DIREITA, LIBERAR_ULTIMO_SEMAFORO, LIBERAR_ANTEPENULTIMO_SEMAFORO, SEGUIR_RETO, LIBERAR_PRE_ANTEPENULTIMO_SEMAFORO,
      ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_ULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_SEMAFORO_DE_INICIO_DUPLO,
      ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_ULTIMO_SEMAFORO, LIBERAR_PENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO,
      VIRAR_DIREITA, SEGUIR_RETO, LIBERAR_ULTIMO_SEMAFORO
    },
    
    
    {
      ADQUIRIR_SEMAFORO, SEGUIR_RETO, ADQUIRIR_SEMAFORO, VIRAR_DIREITA, LIBERAR_SEMAFORO_DE_INICIO_DUPLO, LIBERAR_PENULTIMO_SEMAFORO,
      ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_ULTIMO_SEMAFORO, LIBERAR_ANTEPENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO,
      SEGUIR_RETO, LIBERAR_ANTEPENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_ANTEPENULTIMO_SEMAFORO,
      LIBERAR_ULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_ANTEPENULTIMO_SEMAFORO,  ADQUIRIR_SEMAFORO, VIRAR_DIREITA,
      LIBERAR_PENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_PENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, 
      ADQUIRIR_SEMAFORO, VIRAR_DIREITA, LIBERAR_ULTIMO_SEMAFORO, LIBERAR_ANTEPENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, 
      SEGUIR_RETO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO,
      LIBERAR_PRE2X_ANTEPENULTIMO_SEMAFORO, LIBERAR_ULTIMO_SEMAFORO, LIBERAR_PRE4X_ANTEPENULTIMO_SEMAFORO, SEGUIR_RETO,
      LIBERAR_PENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_ULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, 
      ADQUIRIR_SEMAFORO, VIRAR_DIREITA, LIBERAR_ULTIMO_SEMAFORO, LIBERAR_PRE4X_ANTEPENULTIMO_SEMAFORO,
      LIBERAR_PRE5X_ANTEPENULTIMO_SEMAFORO, LIBERAR_PRE_ANTEPENULTIMO_SEMAFORO
    },
    
    
    {
      VIRAR_ESQUERDA, ADQUIRIR_SEMAFORO, SEGUIR_RETO, ADQUIRIR_SEMAFORO, VIRAR_ESQUERDA, LIBERAR_SEMAFORO_DE_INICIO_DUPLO,
      LIBERAR_SEMAFORO_DE_INICIO_QUADRUPLO, LIBERAR_PENULTIMO_SEMAFORO, VIRAR_DIREITA, LIBERAR_ULTIMO_SEMAFORO, 
      ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, VIRAR_ESQUERDA, LIBERAR_ULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO,
      VIRAR_DIREITA, LIBERAR_PRE_ANTEPENULTIMO_SEMAFORO, LIBERAR_ULTIMO_SEMAFORO, VIRAR_ESQUERDA, LIBERAR_PENULTIMO_SEMAFORO,
      ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, VIRAR_DIREITA, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO,
      VIRAR_ESQUERDA, LIBERAR_PRE_ANTEPENULTIMO_SEMAFORO, SEGUIR_RETO, LIBERAR_ULTIMO_SEMAFORO, VIRAR_ESQUERDA, SEGUIR_RETO,
      ADQUIRIR_SEMAFORO, VIRAR_ESQUERDA, LIBERAR_PRE4X_ANTEPENULTIMO_SEMAFORO, LIBERAR_PRE3X_ANTEPENULTIMO_SEMAFORO,
      LIBERAR_ANTEPENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, VIRAR_DIREITA, LIBERAR_PENULTIMO_SEMAFORO, LIBERAR_PRE2X_ANTEPENULTIMO_SEMAFORO,
      ADQUIRIR_SEMAFORO, VIRAR_ESQUERDA, LIBERAR_ULTIMO_SEMAFORO, LIBERAR_PENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO,
      VIRAR_DIREITA, LIBERAR_ULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, VIRAR_ESQUERDA, LIBERAR_ANTEPENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO,
      ADQUIRIR_SEMAFORO, VIRAR_DIREITA, LIBERAR_ANTEPENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, VIRAR_ESQUERDA,
      LIBERAR_ANTEPENULTIMO_SEMAFORO, SEGUIR_RETO, LIBERAR_ULTIMO_SEMAFORO
    },
    
    
    {
      ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, VIRAR_DIREITA, VIRAR_DIREITA, LIBERAR_ANTEPENULTIMO_SEMAFORO,
      LIBERAR_ULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, VIRAR_ESQUERDA, LIBERAR_PRE_ANTEPENULTIMO_SEMAFORO,
      LIBERAR_ULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_ANTEPENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, VIRAR_DIREITA, 
      LIBERAR_PENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_PENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO,
      LIBERAR_PENULTIMO_SEMAFORO, VIRAR_DIREITA, LIBERAR_ULTIMO_SEMAFORO, SEGUIR_RETO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO,
      ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, VIRAR_ESQUERDA, LIBERAR_ULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, VIRAR_DIREITA,
      LIBERAR_PRE_ANTEPENULTIMO_SEMAFORO, LIBERAR_ULTIMO_SEMAFORO, LIBERAR_PRE3X_ANTEPENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, VIRAR_DIREITA,
      LIBERAR_ANTEPENULTIMO_SEMAFORO, LIBERAR_PRE3X_ANTEPENULTIMO_SEMAFORO, VIRAR_ESQUERDA, LIBERAR_ULTIMO_SEMAFORO, SEGUIR_RETO,
      ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, VIRAR_DIREITA, ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_PENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO,
      SEGUIR_RETO, ADQUIRIR_SEMAFORO, VIRAR_DIREITA, LIBERAR_PRE2X_ANTEPENULTIMO_SEMAFORO, LIBERAR_PENULTIMO_SEMAFORO,
      LIBERAR_ANTEPENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, ADQUIRIR_SEMAFORO, SEGUIR_RETO, LIBERAR_ULTIMO_SEMAFORO,
      LIBERAR_ANTEPENULTIMO_SEMAFORO, ADQUIRIR_SEMAFORO, VIRAR_ESQUERDA, LIBERAR_ANTEPENULTIMO_SEMAFORO, LIBERAR_ULTIMO_SEMAFORO
    }
  };
  
  /* Armazena os valores inicias de cada carro respectivamente,
     cada vetor armazena sentido, posicao X e posicao Y  do carro respectivamente */
  private final int[][] CONFIGURACOES_INICIAIS = 
  {
    {2, 342, 269}, {0, 282, 665}, {2, 78, 401}, {0, 414, 137},
    {2, 605, 5},   {2, 342, 5},   {0, 18, 5},   {2, 606, 269}
  };
  
  /* ***************************************************************
  * Metodo: getPercurso
  * Funcao: retorna o vetor percurso para um carro de acordo com o indice recebido
  * Parametros: indice = indice que informama qual o vetor percurso requerido
  * Retorno: int[] = vetor percurso
  *************************************************************** */
  public int[] getPercurso(int indice)
  {
    return PERCURSOS[indice];
  }//fim do getPercurso
  
  /* ***************************************************************
  * Metodo: getConfiguracaoInicial
  * Funcao: retorna um vetor com as configuracoes iniciais do carro de acordo com o indice recebido
  * Parametros: indice = indice que informa qual a configuracao inicial requerida
  * Retorno: int[] = vetor com configuracao inicial de um carro
  *************************************************************** */
  public int[] getConfiguracaoInicial(int indice)
  {
    return CONFIGURACOES_INICIAIS[indice];
  }//fim do getConfiguracaoInicial
}//fim da classe enum Percursos
